### ISSUE TITLE
Configs file should use .env file

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/template#155]
Use some dep from deno.land to add .env file support and pull them into the configs.ts file.

**Comment by Amatsagu** [comment]
Well, that's generally just a choice - in the end it doesn't really matter what you'll use.
For environmental file you can use https://deno.land/x/dotenv@v3.1.0

**Comment by Reboot-Codes** [comment]
Resolved: A `.env` file will supply private data to a `config.ts` file in each template type.
